Repository StatCan/jupyter-notebooks, pull requests merged in 2020-05, with the labels that each got.

#9 feat: add python+mc self-serve minio example
  self-serve-storage/R/Storage Examples.ipynb
  self-serve-storage/R/daaas_storage.R
  self-serve-storage/R/example-folder/untitled.txt
  self-serve-storage/R/example.txt
  self-serve-storage/R/kubeflow-minio-option.png
  self-serve-storage/mc/Storage Examples.ipynb
  self-serve-storage/mc/example.txt
  self-serve-storage/mc/kubeflow-minio-option.png
  self-serve-storage/python/Storage Examples.ipynb
  self-serve-storage/python/daaas_storage.py
  self-serve-storage/python/example.txt
  self-serve-storage/python/kubeflow-minio-option.png
  self-serve-storage/python/progress.py
Labels: component/jupyter, component/kubeflow, current-sprint, priority/important-soon

#13 feat: add statscan_data example for R and Python
  statscan_data/ExtractionViaPython.ipynb
  statscan_data/ExtractionViaR.ipynb
Labels: component/jupyter, kind/docs

#10 simple statscan data access with Python and R
  statscan_data/ExtractionViaPython.ipynb
  statscan_data/ExtractionViaR.ipynb
Labels: component/jupyter, kind/docs, priority/important-soon

#15 feat(minio-sql): example notebooks/scripts for sql queries to minio
  querySQL/MinioSQL.ipynb
  querySQL/daaas_storage_boto3.py
  querySQL/data/.gitignore
  querySQL/data/get_data.sh
  querySQL/power_bi_quickstart.py
Labels: component/jupyter, component/storage, kind/feature

#16 docs: add documentation and warnings for technical helper files
  mapreduce-pipeline/defaults.py
  querySQL/daaas_storage_boto3.py
  querySQL/power_bi_quickstart.py
  self-serve-storage/R/daaas_storage.R
  self-serve-storage/python/daaas_storage.py
  self-serve-storage/python/progress.py
Labels: component/jupyter, kind/docs
